### ISSUE TITLE
Unable to load Home Assistant interface via port 8123 through Nebula

### ISSUE THREAD

**Issue by V13Axel** [mr-ransel/addon-nebula#2]
I've got the nebula add-on installed and running successfully (As of the fixes in PR #1 ), and I can confirm that:

1. My Home Assistant server **is** connected to my overlay network
2. I **can** ping my Home Assistant server via its nebula IP
3. My port 8123 firewall rule is present (`level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:8123 groups:[axel] host: ip: proto:6 startPort:8123]"`)

However, I can't seem to actually load the web interface via port 8123. Should I expect that to be working, or is there something else that I need to configure for that?

**Comment by mr-ransel** [comment]
Yeah, I know there's a few steps needed. There's a particular magic combination of iptables rules I need to figure out as a `post_up` equivalent from [wireguard](https://github.com/hassio-addons/addon-wireguard/blob/main/wireguard/rootfs/etc/cont-init.d/config.sh#L102-L103), but after fiddling with it awhile last weekend I got fed up, but I'll re-visit it with fresh eyes soon.

Essentially I need to figure out iptables magic is necessary to forward traffic from nebula -> the local interface inside the docker container that surfaces home assistant. 

So far I've worked out that in order to advertise the route to home assistant, first the nebula-cert command that you use to sign the cert being used by home assistant needs a `-subnets 172.30.32.0/23` (approximately), then you need to, on the devices that want to route to home assistant, add the home assistant docker-internal ip (for me it's 172.30.32.1) as an `unsafe_route` in the config so it's willing to route those IP(s) over the nebula interface

That's where I got tired and stopped, but pretty sure the iptables config is what I need to work out next.

**Comment by mr-ransel** [comment]
Heh, if you can't tell it's very much still in development. I was also working on the bash-scripts to be used to do all the nebula-cert management. I'll throw that into master as well in the semi-developed state that it's in so far.

**Comment by mr-ransel** [comment]
@V13Axel I came back to this today with a clear head and got it sorted out and working forwarding not just Home Assistant, but also the entire home network. (The only behavior for now, but later this will be configurable).

If you want to try again these were the manual changes needed (after my code change):
* Your `advertise_addrs` clause in your nebula config for HASS matches any external port-forwarding you're doing
* Make sure in your nebula client configs you include an `unsafe_routes` clause matching the IP range you'd like to access over the Nebula tunnel (in my case, on my phone I added an `unsafe_route` for `192.168.X.0/24` to access my whole network)
* You'll need to sign the HASS addon certificate to include the above `unsafe_route` subnet. If you're using my script to generate them, you can just add the following to the end of your host.txt file on the line generating your HASS certs: `-subnets 192.168.X.0/24`

Next I'll get on to handling all this automatically in the UI so it will spit out server and client configs and certs/keys automatically for you, but for now it's stably granting me access to the HASS and home network IPs. Next will be also handling DNS seamlessly as well.

**Comment by V13Axel** [comment]
Oh, neat! I'll definitely give this a look at some point shortly then, thanks for the update. 

Only reason I didn't look into this too hard is that I had a short-term need at the time and ended up putting together a temporary solution of setting up a reverse-proxy on one of my other homelab servers that already had Nebula up and running and then accessing it that way. Not perfect, but it got the job done in a pinch; We had needed to remotely monitor some things for my wife's reptiles while we were out of town a while back.

However, that need will definitely continue to recur, which means it's worth it for me to look into this!
